### ISSUE TITLE
Smart config problem

### ISSUE THREAD

**Issue by tangkechen** [particle-iot/android-app#5]
HI
 Now I am interesting how Android APP config SPARK core over WIFI,I hava found when I enter SSID's password and press CONNECT button , amount of data is been sent out from my android device ,and the speed is about 512k/s,when I look for the process of data transformation, I find the data had sent to 224.0.1.187:5685, google this ip and find the IP is IANA and a multicast address . 
Several questions confuse me:

1.How the APP does in order to send SSID's password?what the format of multicast information?what is the protocol?what is the detail of protocol?where is the source shows this process?can I change the IP to 224.0.1.186.. and port to 5686..?can I add other information in the multicast information,such as port's initial level?when the multicast information has been successfully sent ,what the SPARK core replies?

2.what does the SPARK core do when it received the multicast information?
where is the source?

can you answer the above question ?

Best regards
FRT

**Comment by towynlin** [comment]
Hi @tangkechen, great question!

The mobile app uses TI's Smart Config technology to broadcast AES encrypted Wi-Fi credentials to listening CC3000 Wi-Fi modules. TI does not make the source code for Smart Config available. See TI's [CC3000 Smart Config](http://processors.wiki.ti.com/index.php/CC3000_Smart_Config) page for more info.

As explained there, after the Wi-Fi module successfully connects to the Wi-Fi network, it multicasts mDNS packets locally to tell the mobile app that it has connected. Our call into the CC3000 API to send mDNS is in [spark_wlan.cpp on line 540](https://github.com/spark/core-firmware/blob/master/src/spark_wlan.cpp#L540).

Check out the [CC3000 firmware API documentation](http://software-dl.ti.com/ecs/simplelink/cc3000/public/doxygen_API/v1.12/html/index.html).

Separate from Smart Config, the Spark Core also announces its presence on the local network with a multicast [CoAP](https://datatracker.ietf.org/doc/draft-ietf-core-coap/) message that includes the Core ID. See [spark_utilities.cpp line 542](https://github.com/spark/core-firmware/blob/master/src/spark_utilities.cpp#L542).

This message is sent on the [IANA registered multicast IP address](http://www.iana.org/assignments/multicast-addresses/multicast-addresses.xhtml) for "All CoAP Nodes" 224.0.1.187. The default CoAP port according to the CoAP spec is 5683.

If you write firmware in the [web IDE](https://www.spark.io/build), you can't change this behavior, but you can additionally send your own UDP datagrams to any address and port that you want. See Spark's [UDP documentation](http://docs.spark.io/#/firmware/communication-udp).

If you build the firmware locally (instructions in the [core-firmware](https://github.com/spark/core-firmware) README) you can change the [IP or port in spark_utilities.cpp](https://github.com/spark/core-firmware/blob/master/src/spark_utilities.cpp#L566) or the format of the [presence announcement](https://github.com/spark/core-communication-lib/blob/master/src/spark_protocol.cpp#L695) in the core-communication-lib.

Hope that answers all your questions! In the future a better place for questions like this is in the [Spark Community](https://community.spark.io/)! Cheers!
